# Generated by Django 5.1.4 on 2025-01-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_secretquestion_created_at_secretquestion_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretquestion',
            name='updated_at',
        ),
    ]
